MVC2023_v3.0/Models/Professor.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MVC2023_v3._0.Models;
[Table("professors")]
public partial class Professor
{
    [Key]
    public int Afm { get; set; }

    public string Name { get; set; } = null!;

    public string Surname { get; set; } = null!;

    public string Department { get; set; } = null!;

    public string Username { get; set; } = null!;

    public virtual ICollection<Course> Courses { get; } = new List<Course>();

    public virtual User UsernameNavigation { get; set; } = null!;
}

MVC2023_v3.0/Controllers/ProfessorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVC2023_v3._0.Models;

namespace MVC2023_v3._0.Controllers
{
    public class ProfessorsController : Controller
    {
        private readonly MvcDbContext _context;

        public ProfessorsController(MvcDbContext context)
        {
            _context = context;
        }

        // GET: Professors
        public async Task<IActionResult> Index()
        {
            var mvcDbContext = _context.Professors.Include(p => p.UsernameNavigation);
            return View(await mvcDbContext.ToListAsync());
        }

        public async Task<IActionResult> ShowAllGraded(string? id)
        {
            if (id == null || _context.Professors == null)
            {
                return NotFound();
            }
            
            var professor = await _context.Professors
                .Include(p => p.UsernameNavigation)
                .FirstOrDefaultAsync(m => m.Username == id);

            if (professor == null)
            {
                return NotFound();
            }

            List<Course> courses = _context.Courses
                .Where(x => x.Afm == professor.Afm)
                .ToList();

            List<CourseHasStudent> elements = _context.CourseHasStudents
                .Where(x => x.GradeCourseStudent >= 0)
                .ToList();
            


            var grades = from x in courses
                         join y in elements on x.IdCourse equals y.IdCourse 
                         where x.Afm == professor.Afm
                         select new Grade
                         {     
                             RegistrationNumber = y.RegistrationNumber,
                             IdCourse= x.IdCourse,
                             CourseTitle = x.CourseTitle,
                             GradeCourseStudent = y.GradeCourseStudent

                         };
            return View(grades);
            //Debugger
            /*    foreach (var course in courses)
            {
                System.Diagnostics.Debug.WriteLine(course.CourseTitle);
            }*/
        }

        public async Task<IActionResult> EditGrade(string? id)
        {
            if (id == null || _context.Professors == null)
            {
                return NotFound();
            }

            var professor = await _context.Professors
                .Include(p => p.UsernameNavigation)
                .FirstOrDefaultAsync(m => m.Username == id);

            if (professor == null)
            {
                return NotFound();
            }

            List<Course> courses = _context.Courses
                .Where(x => x.Afm == professor.Afm)
                .ToList();

            List<CourseHasStudent> elements = _context.CourseHasStudents
                .DefaultIfEmpty()
                .ToList();

            var grades = from x in courses
                         join y in elements on x.IdCourse equals y.IdCourse
                         where x.Afm == professor.Afm && y.GradeCourseStudent == 0
                         select new Grade
                         {
                             RegistrationNumber = y.RegistrationNumber,
                             IdCourse = x.IdCourse,
                             CourseTitle = x.CourseTitle,
                             GradeCourseStudent = y.GradeCourseStudent
                         };

            return View(grades);
            //Debugger
            /*    foreach (var course in courses)
            {
                System.Diagnostics.Debug.WriteLine(course.CourseTitle);
            }*/
        }

        public async Task<IActionResult> SaveNewGrade(int grade, int regnum, int idcourse)
        {
            List<Course> courses = _context.Courses
                .Where(x => x.IdCourse == idcourse)
                .ToList();

            List<CourseHasStudent> elements = _context.CourseHasStudents
                .DefaultIfEmpty()
                .Where(x => x.RegistrationNumber == regnum && x.IdCourse == idcourse)
                .ToList();

            CourseHasStudent coursehasstudent = _context.CourseHasStudents
                .Where(x => x.RegistrationNumber == regnum && x.IdCourse == idcourse)
                .SingleOrDefault();

            coursehasstudent.GradeCourseStudent = grade;

            _context.Update(coursehasstudent);
            _context.SaveChanges();

            var grades = from x in courses
                         join y in elements on x.IdCourse equals y.IdCourse
                         where x.IdCourse == y.IdCourse
                         select new Grade
                         {
                             RegistrationNumber = y.RegistrationNumber,
                             IdCourse = x.IdCourse,
                             CourseTitle = x.CourseTitle,
                             GradeCourseStudent = grade
                         };


            /*foreach (var result in grades)
            {
                result.GradeCourseStudent = grade;

            }*/

            /*CourseHasStudent f = _context.CourseHasStudents.SingleOrDefault(x => x.IdCourse == idcourse && x.RegistrationNumber == regnum);
            f.GradeCourseStudent = grade; 
            _context.SaveChanges();*/
                                    
            return View(coursehasstudent);
        }

        // GET: Professors/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Professors == null)
            {
                return NotFound();
            }

            var professor = await _context.Professors.FindAsync(id);
            if (professor == null)
            {
                return NotFound();
            }
            ViewData["Username"] = new SelectList(_context.Users, "Username", "Username", professor.Username);
            return View(professor);
        }

        // POST: Professors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Afm,Name,Surname,Department,Username")] Professor professor)
        {
            if (id != professor.Afm)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(professor);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProfessorExists(professor.Afm))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Username"] = new SelectList(_context.Users, "Username", "Username", professor.Username);
            return View(professor);
        }

        

        private bool ProfessorExists(int id)
        {
          return _context.Professors.Any(e => e.Afm == id);
        }
    }
}

MVC2023_v3.0/Views/Professors/EditGrade.cshtml
@model IEnumerable<MVC2023_v3._0.Models.Grade>

@{
    ViewData["Title"] = "EditGrade";
}

<h1>Professors</h1>
<h3>All graded</h3>


<table class="table">
    <thead>
        <tr>
            <th>
                Registration Number
            </th>
            <th>
                Course
            </th>
            <th>
                Score
            </th>
        </tr>
    </thead>
    <tbody>
        @using (Html.BeginForm("SaveNewGrade", "Professors"))
        {
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                    @Html.DisplayFor(modelItem => item.RegistrationNumber)
                    </td>
                    <td>
                    @Html.DisplayFor(modelItem => item.CourseTitle)
                    </td>
                    <td>
                    <input type="text" name="grade" />
                    </td>
                    <td>
                    <input type="hidden" name="regnum" value="@item.RegistrationNumber"/>
                    <input type="hidden" name="idcourse" value="@item.IdCourse"/>
                    <input type="submit" action="SaveNewGrade" value="Save"/>
                    </td>
                    </tr>
        }
        } 
    </tbody>
</table>
            

MVC2023_v3.0/Views/Professors/Index.cshtml
@model IEnumerable<MVC2023_v3._0.Models.Professor>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Surname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Department)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UsernameNavigation)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
         <tr>
            <td>
                @TempData["name"]
            </td>
            <td>
                @TempData["surname"]
            </td>
            <td>
                @TempData["department"]
            </td>
            </tr>
    </tbody>
</table>
<div>
    <a asp-action="ShowAllGraded" asp-route-id="@TempData["username"]"> Show all graded courses </a> |
    <a asp-action="EditGrade" asp-route-id="@TempData["username"]"> Put a grade </a> 
</div>

MVC2023_v3.0/Views/Professors/SaveNewGrade.cshtml
@model MVC2023_v3._0.Models.CourseHasStudent

@{
    ViewData["Title"] = "SaveNewGrade";
}

<h1>All changes saved.</h1>

MVC2023_v3.0/Views/Professors/ShowAllGraded.cshtml
@model IEnumerable<MVC2023_v3._0.Models.Grade>

@{
    ViewData["Title"] = "ShowAllGraded";
}

<h1>Professors</h1>
<h3>All graded</h3>


<table class="table">
    <thead>
        <tr>
            <th>
                Registration Number
            </th>
            <th>
                Course
            </th>
            <th>
                Score
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
                <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.RegistrationNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CourseTitle)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.GradeCourseStudent)
                </td>
                </tr>
        }
    </tbody>
</table>