MVC2023_v3.0/Models/Secretary.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MVC2023_v3._0.Models;
[Table("secretaries")]
public partial class Secretary
{
    [Key]
    public int Phonenumber { get; set; }

    public string Name { get; set; } = null!;

    public string Surname { get; set; } = null!;

    public string Department { get; set; } = null!;

    public string Username { get; set; } = null!;

    public virtual User UsernameNavigation { get; set; } = null!;
}

MVC2023_v3.0/Controllers/SecretariesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVC2023_v3._0.Models;

namespace MVC2023_v3._0.Controllers
{
    public class SecretariesController : Controller
    {
        private readonly MvcDbContext _context;

        public SecretariesController(MvcDbContext context)
        {
            _context = context;
        }

        // GET: Secretaries
        public async Task<IActionResult> Index()
        {
            var mvcDbContext = _context.Secretaries.Include(s => s.UsernameNavigation);
            return View(await mvcDbContext.ToListAsync());
        }

        public async Task<IActionResult> ShowAllCourses(string? id)
        {
            List<Professor> professors = _context.Professors.ToList();
            List<Course> courses = _context.Courses.ToList();

            var grade = from x in professors
                        join y in courses on x.Afm equals y.Afm
                        select new ProfessorName
                        {
                            CourseTitle = y.CourseTitle,
                            CourseSemester = y.CourseSemester,
                            Name = x.Name
                        };
            return View(grade);
        }

        // GET: Secretaries/CreateStudent
        public IActionResult CreateStudent()
        {
            ViewData["Username"] = new SelectList(_context.Users, "Username", "Username");
            return View();
        }

        // GET: Secretaries/CreateProfessor
        public IActionResult CreateProfessor()
        {
            ViewData["Username"] = new SelectList(_context.Users, "Username", "Username");
            return View();
        }

        // GET: Secretaries/CreateCourse
        public IActionResult CreateCourse()
        {
            ViewData["Username"] = new SelectList(_context.Users, "Username", "Username");
            return View();
        }

        // POST: Secretaries/CreateNewStudent
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateNewStudent([Bind("RegistrationNumber,Name,Surname,Department,Username")] Student student,string pwd)
        {
                User user = new User();
                user.Username = student.Username;
                user.Role = "Student";
                user.Password = pwd;
                _context.Users.Add(user);
                _context.Students.Add(student);
                _context.SaveChanges();

            return View(student);
        }

        // POST: Secretaries/CreateNewProfessor
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateNewProfessor([Bind("Afm,Name,Surname,Department,Username")] Professor professor, string pwd)
        {
            User user = new User();
            user.Username = professor.Username;
            user.Role = "Professor";
            user.Password = pwd;
            _context.Users.Add(user);
            _context.Professors.Add(professor);
            _context.SaveChanges();

            return View(professor);
        }

        // POST: Secretaries/CreateNewCourse
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateNewCourse([Bind("IdCourse,CourseTitle,CourseSemester,Afm")] Course course)
        {
            _context.Courses.Add(course);
            _context.SaveChanges();
            return View(course);
        }

        public IActionResult SetCourseStudent()
        {
            ViewData["Username"] = new SelectList(_context.Users, "Username", "Username");
            return View();
        }

        // POST: Secretaries/CreateNewCourse
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Setchs([Bind("RegistrationNumber,IdCourse")] CourseHasStudent chs)
        {
            var c = _context.CourseHasStudents
                             .OrderByDescending(x => x.IdPk)
                             .Take(1)
                             .Select(x => x.IdPk)
                             .ToList()
                             .FirstOrDefault();
            chs.GradeCourseStudent = 0;
            chs.IdPk = c + 1;

            _context.CourseHasStudents.Add(chs);
            _context.SaveChanges();
            return View(chs);
        }
    }
}

MVC2023_v3.0/Views/Secretaries/Create.cshtml
@model MVC2023_v3._0.Models.Secretary

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Secretary</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Phonenumber" class="control-label"></label>
                <input asp-for="Phonenumber" class="form-control" />
                <span asp-validation-for="Phonenumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Surname" class="control-label"></label>
                <input asp-for="Surname" class="form-control" />
                <span asp-validation-for="Surname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Department" class="control-label"></label>
                <input asp-for="Department" class="form-control" />
                <span asp-validation-for="Department" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Username" class="control-label"></label>
                <select asp-for="Username" class ="form-control" asp-items="ViewBag.Username"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVC2023_v3.0/Views/Secretaries/CreateCourse.cshtml
@model MVC2023_v3._0.Models.Course

@{
    ViewData["Title"] = "CreateCourse";
}

<h1>Create new course</h1>
<div class="row">
    <div class="col-md-4">
        <form asp-controller="Secretaries" asp-action="CreateNewCourse">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdCourse" class="control-label"></label>
                <input asp-for="IdCourse" class="form-control" />
                <span asp-validation-for="IdCourse" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CourseTitle" class="control-label"></label>
                <input asp-for="CourseTitle" class="form-control" />
                <span asp-validation-for="CourseTitle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CourseSemester" class="control-label"></label>
                <input asp-for="CourseSemester" class="form-control" />
                <span asp-validation-for="CourseSemester" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Afm" class="control-label"></label>
                <input asp-for="Afm" class="form-control" />
                <span asp-validation-for="Afm" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="CreateNewCourse" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

MVC2023_v3.0/Views/Secretaries/CreateNewCourse.cshtml
@model MVC2023_v3._0.Models.Course

@{
    ViewData["Title"] = "CreateNewCourse";
}

<h1>You just created a new course.</h1>

MVC2023_v3.0/Views/Secretaries/CreateNewProfessor.cshtml
@model MVC2023_v3._0.Models.Professor

@{
    ViewData["Title"] = "CreateNewProfessor";
}

<h1>You just created the new professor.</h1>

MVC2023_v3.0/Views/Secretaries/CreateNewStudent.cshtml
@model MVC2023_v3._0.Models.Student

@{
    ViewData["Title"] = "CreateNewStudent";
}

<h1>You just created the new student.</h1>

MVC2023_v3.0/Views/Secretaries/CreateProfessor.cshtml
@model MVC2023_v3._0.Models.Professor

@{
    ViewData["Title"] = "CreateProfessor";
}

<h1>Create new professor</h1>
<div class="row">
    <div class="col-md-4">
        <form asp-controller="Secretaries" asp-action="CreateNewProfessor">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Afm" class="control-label"></label>
                <input asp-for="Afm" class="form-control" />
                <span asp-validation-for="Afm" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Surname" class="control-label"></label>
                <input asp-for="Surname" class="form-control" />
                <span asp-validation-for="Surname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Department" class="control-label"></label>
                <input asp-for="Department" class="form-control" />
                <span asp-validation-for="Department" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Username" class="control-label"></label>
                <input asp-for="Username" class="form-control" asp-items="ViewBag.Username"></input>
            </div>
            <div class="form-group">
                <label class="control-label">Password</label>
                <input type="password" name="pwd" id="pwd" class="form-control"></input>
            </div>

            <div class="form-group">
                <input type="submit" value="CreateNewProfessor" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

MVC2023_v3.0/Views/Secretaries/CreateStudent.cshtml
@model MVC2023_v3._0.Models.Student

@{
    ViewData["Title"] = "CreateStudent";
}

<h1>Create new Student</h1>
<div class="row">
    <div class="col-md-4">
        <form asp-controller="Secretaries" asp-action="CreateNewStudent">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="RegistrationNumber" class="control-label"></label>
                <input asp-for="RegistrationNumber" class="form-control" />
                <span asp-validation-for="RegistrationNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Surname" class="control-label"></label>
                <input asp-for="Surname" class="form-control" />
                <span asp-validation-for="Surname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Department" class="control-label"></label>
                <input asp-for="Department" class="form-control" />
                <span asp-validation-for="Department" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Username" class="control-label"></label>
                <input asp-for="Username" class="form-control" asp-items="ViewBag.Username"></input>
            </div>
            <div class="form-group">
                <label class="control-label">Password</label>
                <input type="password" name="pwd" id="pwd" class="form-control" ></input>
            </div>
          
            <div class="form-group">
                <input type="submit" value="CreateNewStudent" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

MVC2023_v3.0/Views/Secretaries/Index.cshtml
@model IEnumerable<MVC2023_v3._0.Models.Secretary>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Surname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Department)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                @TempData["name"]
            </td>
            <td>
                @TempData["surname"]
            </td>
            <td>
                @TempData["department"]
            </td>
            </tr>
    </tbody>
</table>
<div>
    <a asp-action="CreateStudent" asp-route-id="@TempData["phonenumber"]">Create new Student</a>|
    <a asp-action="CreateProfessor" asp-route-id="@TempData["phonenumber"]">Create new Professor</a>|
    <a asp-action="CreateCourse" asp-route-id="@TempData["phonenumber"]">Create new Course</a>|
    <a asp-action="SetCourseStudent" asp-route-id="@TempData["username"]">Assign a course</a>|
    <a asp-action="ShowAllCourses" asp-route-id="@TempData["username"]">ShowAllCourses</a>
</div>

MVC2023_v3.0/Views/Secretaries/SetCourseStudent.cshtml
@model MVC2023_v3._0.Models.CourseHasStudent

@{
    ViewData["Title"] = "SetCourseStudent";
}

<h1>Set course to student</h1>
<div class="row">
    <div class="col-md-4">
        <form asp-controller="Secretaries" asp-action="Setchs">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="RegistrationNumber" class="control-label"></label>
                <input asp-for="RegistrationNumber" class="form-control" />
                <span asp-validation-for="RegistrationNumber" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="IdCourse" class="control-label"></label>
                <input asp-for="IdCourse" class="form-control" />
                <span asp-validation-for="IdCourse" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Setchs" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

MVC2023_v3.0/Views/Secretaries/Setchs.cshtml
@model MVC2023_v3._0.Models.CourseHasStudent

@{
    ViewData["Title"] = "Setchs";
}

<h1>You just asigned a lesson to a student</h1>se to a student.</h1>

MVC2023_v3.0/Views/Secretaries/ShowAllCourses.cshtml
@model IEnumerable<MVC2023_v3._0.Models.ProfessorName>

@{
    ViewData["Title"] = "ShowAllCourses";
}

<h1>Students</h1>
<h3>All grades for all courses</h3>


<table class="table">
    <thead>
        <tr>
            <th>
                Course
            </th>
            <th>
                Semester
            </th>
            <th>
                Professor
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.CourseTitle)
                </td>
                 <td>
                    @Html.DisplayFor(modelItem => item.CourseSemester)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>

            </tr>
        }
    </tbody>
</table>